version: "3.8"
services:
  db:
    image: "postgres:16"
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass1234

  goapi:
    image: goapi:latest
    build: ./
    restart: always
    container_name: goapi
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db
